### ISSUE TITLE
Update to remove hacktober fest and market as a general tool

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaCommunity/your-first-julia-pr#3]

**Comment by SaschaMann** [comment]
Other than updating copy, you'd only have to change https://github.com/JuliaCommunity/your-first-julia-pr/blob/14d991852c7718d452e7b72d59ff54b28c0546f7/main.go#L64 to include whatever label people use for good first PRs (`good-first-issue`?)

**Comment by SaschaMann** [comment]
Duplicate of #8
