### ISSUE TITLE
How does this detect Julia repos

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaCommunity/your-first-julia-pr#5]
@SaschaMann Hey, is this using the repo language to detect Julia projects?

**Comment by SaschaMann** [comment]
Yes, it performs the following GitHub Search: `is:issue is:open language:julia label:hacktoberfest` and then excludes all repos that haven't had any activity in the last ~6 months

**Comment by logankilpatrick** [comment]
Any idea why: https://github.com/FluxML/fluxml.github.io/issues/107 doesn't show up?

**Comment by SaschaMann** [comment]
Because the repo language is Javascript. I can see if I can adjust the search query to cover repos containing Julia, or manually add that repo

**Comment by SaschaMann** [comment]
For now the count will be wrong (it'll always be 1) but I don't have time to debug why https://github.com/JuliaCommunity/your-first-julia-pr/blob/3070884f7cccc238e2b8b1f13445c1c1e3a528a8/main.go#L85-L105 doesn't find the issues atm.
