### ISSUE TITLE
Repositories listed in the `Projects` section

### ISSUE THREAD

**Issue by thazhemadam** [JuliaCommunity/your-first-julia-pr#6]
Under the projects section on the [web page](https://juliacommunity.github.io/your-first-julia-pr/), repositories that are NOT participating in Hacktoberfest have also been listed.

It looks like all repositories that have issues tagged with the `hacktoberfest` label are considered to be participating (see [here](https://github.com/JuliaCommunity/your-first-julia-pr/blob/14d991852c7718d452e7b72d59ff54b28c0546f7/main.go#L61-L78)).

However, only repositories that have the "topic" `hacktoberfest` added are considered to be participating in Hacktoberfest (see rules [here](https://hacktoberfest.digitalocean.com/)) and there are a few repositories currently listed which DON'T have the `hacktoberfest` topic.

**Comment by SaschaMann** [comment]
Repos don't have to add the topic to participate, they can also tag individual PRs with `hacktoberfest-accepted` to make them count. Setting the topic acts as an opt-in for all PRs. There are some projects that only want new contributions on certain issues or don't want the overall attention from opting in by default but who are happy to tag individual PRs on request.

I assume that if you tag an issue with `hacktoberfest`, you're interested in contributions for those issues, so I think it's fair to list them.

---

Let me know if you want me to remove a project of yours that you don't want listed on here, though.

**Comment by thazhemadam** [comment]
I was just thinking of the more general case where issues labelled with `hacktoberfest` long ago get picked up when the repository is no longer interested in participating (for whatever reasons).

But I understand and agree with your reasoning. Fair enough. The more the merrier!
